# Generated by Django 4.1.3 on 2023-04-13 21:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sessionyearmodle',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
