# Generated by Django 4.1.3 on 2023-05-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0006_alter_leavereportstudent_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
    ]
